### ISSUE TITLE
[Bug] Manga with null chapters crashes downloader

### ISSUE THREAD

**Issue by CaedenWhitaker** [Proxymiity/MangaDex.zip#2]
Some [Manga](https://mangadex.org/chapter/bac0ba8e-6896-4425-8c2c-3dc716bfeea4) have a volume number, but no chapter number. As a result, this crashes the downloader (only when attempting to download all chapters). The issue can be seen below:

![image](https://github.com/Proxymiity/MangaDex.zip/assets/97039876/f1b7ef76-6e43-408c-aad7-0d29cea775e0)

I've tested a working solution, but I can't publish my branch and I don't really care enough to fork this.

![image](https://github.com/Proxymiity/MangaDex.zip/assets/97039876/1ca093ce-912f-4fe4-b586-c782b184fe43)

The hack I worked out in `MangaDexZip/queue/actions.py` is the following:

```
        dedup_dict = {}
        for chap in chaps:
            if chap.chapter not in dedup_dict:
                try:
                    dedup_dict[f"Vol.{chap.volume or '?'} Ch.{chap.chapter or '?'}"] = (float(chap.chapter), chap)
                except (ValueError, TypeError):
                    dedup_dict[f"Vol.{chap.volume or '?'} Ch.{chap.chapter or '?'}"] = (-float("inf"), chap)
        for _, pair in sorted(dedup_dict.items(), key=lambda i: i[1][0]):
            chap = pair[1]
            task.add_action(DownloadChapter(chap.id, data_obj=chap, light=self.light, subfolder=True,
                                            append_title=self.append_titles))
```

In essence, using strings to deduplicate the chapters, but still using floats for sorting them. Using -infinity to place any _None_ chapters at the front of the sorted list. This might not be the most elegant solution but it seems to work.

**Comment by Proxymiity** [comment]
Thanks for the report. I think I see what is happening and this may be entirely specific with oneshot chapters. 

I'll craft a quick fix and update the public workers in a bit.

**Comment by Proxymiity** [comment]
> In essence, using strings to deduplicate the chapters, but still using floats for sorting them. Using -infinity to place any None chapters at the front of the sorted list. This might not be the most elegant solution but it seems to work.

To be fair, sorting chapters is just for the visual effect of climbing through chapters. It has no effect on the actual task result whatsoever, so I won't be sorting them by volume+chapter and will keep the chapter sort.

**Comment by Proxymiity** [comment]
Fix ported to prod. Thanks for the bug report. 😇
